InventoryManagement/ViewModels/ChooseProductViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using InventoryManagement.Models;

namespace InventoryManagement.ViewModels
{
    public class ChooseProductViewModel
    {
        public List<Material> Products { get; set; }
        public int SelectedProductID { get; set; }
        public double Quantity { get; set; }
    }
}

InventoryManagement/ViewModels/WorkOrderViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using InventoryManagement.Models;

namespace InventoryManagement.ViewModels
{
    public class WorkOrderViewModel
    {
        public WO_Header WO_Header { get; set; }
        public List<WO_Item> WO_Items { get; set; }
        public List<Status> Status { get; set; }
        public List<Material> Products { get; set; }
        public List<Material> RawMaterials { get; set; }

    }
}

InventoryManagement/Controllers/WorkOrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using InventoryManagement.ViewModels;
using InventoryManagement.Models;

namespace InventoryManagement.Controllers
{
    public class WorkOrderController : Controller
    {
        // Define DBContext Object
        private ApplicationDbContext _context;


        public WorkOrderController()
        {
            // Initialize DBContext Object
            _context = new ApplicationDbContext();
        }


        // GET: WorkOrder
        public ActionResult Index()
        {
            var allWorkOrders = _context.WO_Headers.Include(w => w.Product).Include(w => w.Status).ToList();

            return View(allWorkOrders);
        }

        [Authorize(Roles = "Admin, ProductionDept")]
        public ActionResult ChooseProduct()
        {
            // Initialize viewModel object
            var viewModel = new ChooseProductViewModel()
            {
                SelectedProductID = 0,
                Quantity = 1,
                Products = _context.Materials.Where(m => m.MaterialTypeID == MaterialType.FinishedProduct).ToList()
            };

            return View("ChooseProduct", viewModel);


        }

        [Authorize(Roles = "Admin, ProductionDept")]
        public ActionResult New(ChooseProductViewModel cpViewModel)
        {
            // Inistialize WO items
            List<WO_Item> woItems = new List<WO_Item>();

           
            
            // Get BOM based on selected product id
            var bomHeader = _context.BOM_Headers.Include(b => b.BOM_Items).Where(i => i.ProductID == cpViewModel.SelectedProductID).SingleOrDefault();

            // BOM does not exist
            if (bomHeader == null)
            {
                return View("BOMIsNonExistent");
            }

            // Based on bom item list, initialize wo items

            //foreach (var item in bomHeader.BOM_Items)
            foreach (var item in bomHeader.BOM_Items) 
            {
                WO_Item woItem = new WO_Item();
                woItem.MaterialID = item.MaterialID;
                woItem.Quantity = item.Quantity * cpViewModel.Quantity;
                // FIXME Did NOT SET IN WORK ORDER FORM
                woItem.StatusID = Status.NotStart;   
                woItems.Add(woItem);
            }

            // Inistialize WO Header
            WO_Header woHeader = new WO_Header();
            woHeader.ProductID = cpViewModel.SelectedProductID;
            woHeader.Quantity = cpViewModel.Quantity;
            woHeader.DueDate = DateTime.Now.AddDays(20);
            woHeader.StatusID = Status.NotStart;

            woHeader.Product = _context.Materials.Find(woHeader.ProductID);

            // Initialize viewModel object
            var viewModel = new WorkOrderViewModel()
            {
                WO_Header = woHeader,
                WO_Items = woItems,
                Status = _context.Status.ToList(),
                Products = _context.Materials.Where(m => m.MaterialTypeID == MaterialType.FinishedProduct).ToList(),
                RawMaterials = _context.Materials.Where(m => m.MaterialTypeID == MaterialType.RawMaterial).ToList()

            };
            

            return View("WorkOrderForm", viewModel);

   

        }

        

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(WorkOrderViewModel viewModel)
        {
            
            // Server side validation
            if (!ModelState.IsValid)
            {
                // The form is not valid -> Return the same form to the user

                return View("MaterialForm", viewModel);
            }


            // IF FORM IS VALID

            // Add new device
            if (viewModel.WO_Header.ID == 0)
            {

                // IMPROVEMENT: Could change view model to save next line code
                viewModel.WO_Header.WO_Items = viewModel.WO_Items;
                _context.WO_Headers.Add(viewModel.WO_Header);
            }
            // Update existing device
            else
            {
                //Will implement
            }

            _context.SaveChanges();

            return RedirectToAction("index"); 

        }

    }
}

InventoryManagement/Views/WorkOrder/BOMIsNonExistent.cshtml
@{
    ViewBag.Title = "BOMIsNonExistent";
    Layout = "~/Views/Shared/_MyMasterLayout.cshtml";
}

<h2>BOM does not exist in the System</h2>

InventoryManagement/Views/WorkOrder/ChooseProduct.cshtml
@model InventoryManagement.ViewModels.ChooseProductViewModel

@{
    ViewBag.Title = "ChooseProduct";
    Layout = "~/Views/Shared/_MyMasterLayout.cshtml";
}

<h2>Please Choose a Product</h2>

@using (Html.BeginForm("New", "WorkOrder"))
{


    <div class="panel">

        <div class="panel-body">


            <div class="form-group">
                @Html.LabelFor(m => m.SelectedProductID)
                @Html.DropDownListFor(m => m.SelectedProductID, new SelectList(Model.Products, "ID", "DisplayName"), "Please select a Product", new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.SelectedProductID)
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Quantity)
                @Html.TextBoxFor(m => m.Quantity, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Quantity)

            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-2 col-md-offset-10">
            <button type="submit" class="btn btn-default">Choose</button>
        </div>
    </div>


}

InventoryManagement/Views/WorkOrder/Index.cshtml
@model IEnumerable<InventoryManagement.Models.WO_Header>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MyMasterLayout.cshtml";
}

<h2>All Work Orders in the System</h2>

@if (!Model.Any())
{
    <p>There are no Work orders</p>
}
else
{
    

    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Order ID</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Due Date</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var wo in Model)
            {
                <tr>
                    <td>@wo.ID</td>
                    <td>@wo.Product.Name</td>
                    <td>@wo.Quantity</td>
                    <td>@wo.DueDate.ToShortDateString()</td>
                    <td>@wo.Status.Name</td>
                    
                </tr>

            }

        </tbody>
    </table>
}

InventoryManagement/Views/WorkOrder/WorkOrderForm.cshtml
@model InventoryManagement.ViewModels.WorkOrderViewModel

@{
    ViewBag.Title = "WorkOrderForm";
    Layout = "~/Views/Shared/_MyMasterLayout.cshtml";
}

@if (Model.WO_Header.ID == 0)
{
    <h2 class="page-title">Add New Work Order</h2>
}
else
{
    <h2 class="page-title">Edit Work ORder: @Model.WO_Header.Product.Name</h2>
}


@using (Html.BeginForm("Save", "WorkOrder"))
{
    @Html.ValidationSummary(true, "Please fix the following errors.")



    <!-- PANEL WITH FOOTER -->
    <div class="panel">
        <div class="panel-heading">
            <div class="left">
                <H4>Header</H4>
            </div>
            <div class="right">
                <button type="button" class="btn-toggle-collapse"><i class="lnr lnr-chevron-up"></i></button>
            </div>
        </div>

        <div class="panel-body">

            <div class="form-group">
                @Html.LabelFor(m => m.WO_Header.ProductID)
                @*Html.TextBoxFor(m => m.WO_Header.ProductID, new { @class = "form-control" })*@
                @Html.DropDownListFor(m => m.WO_Header.ProductID, new SelectList(Model.Products, "ID", "DisplayName"), "Please select a Product", new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.WO_Header.ProductID)
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.WO_Header.Quantity)
                @Html.TextBoxFor(m => m.WO_Header.Quantity, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.WO_Header.Quantity)
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.WO_Header.DueDate)
                @Html.TextBoxFor(m => m.WO_Header.DueDate, "{0:yyyy-MM-dd}", new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.WO_Header.DueDate)
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.WO_Header.StatusID)
                @Html.DropDownListFor(m => m.WO_Header.StatusID, new SelectList(Model.Status, "ID", "DisplayName"), "Please select a Status", new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.WO_Header.StatusID)
            </div>
        </div>
    </div>

    <div class="panel">
        <div class="panel-heading">
            <div class="left">
                <H4>Items</H4>
            </div>
            <div class="right">
                <button type="button" class="btn-toggle-collapse"><i class="lnr lnr-chevron-up"></i></button>
            </div>
        </div>

        <div class="panel-body">

            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th>Item No.</th>
                        <th>Material</th>
                        <th>Quantity</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < Model.WO_Items.Count; i++)
                    {
                        <tr>
                            <td>
                                @(i + 1)
                            </td>
                            <td>

                                @*Html.DropDownListFor(m => m.WO_Items[i].MaterialID, new SelectList(Model.RawMaterials, "ID", "DisplayName"), "Please select a Raw Material", new { @class = "form-control" })

        // FIXME: Can not submit if I use selection list
                                *@


                                @Html.TextBoxFor(m => m.WO_Items[i].MaterialID, new { @class = "form-control" })


                            </td>
                            <td>
                                @Html.TextBoxFor(m => m.WO_Items[i].Quantity, new { @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.WO_Items[i].Quantity)

                            </td>
                            <td>
                                @Html.DropDownListFor(m => m.WO_Items[i].StatusID, new SelectList(Model.Status, "ID", "DisplayName"), "Please select a Status", new { @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.WO_Items[i].StatusID)
                            </td>
                        </tr>

                        @Html.HiddenFor(m => m.WO_Items[i].ID)
                        @Html.HiddenFor(m => m.WO_Items[i].WO_HeaderID)

                    }

                </tbody>
            </table>

        </div>
    </div>



    @Html.HiddenFor(m => m.WO_Header.ID)
    @Html.AntiForgeryToken();

    <div class="row">
        <div class="col-md-2 col-md-offset-10">
            <button type="submit" class="btn btn-default">Save</button>
        </div>
    </div>


}

@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
}