InventoryManagement/ViewModels/EnterOrderViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace InventoryManagement.ViewModels
{
    public class EnterOrderViewModel
    {
        public string PostingTypeID { get; set; }
        public int OrderID { get; set; }
    }
}

InventoryManagement/ViewModels/StockPostingViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using InventoryManagement.Models;

namespace InventoryManagement.ViewModels
{
    public class StockPostingViewModel
    {
        public StockPosting_Header StockPosting_Header { get; set; }
        public List<StockPosting_Item> StockPosting_Items { get; set; }

        public List<Material> Products { get; set; }
        public List<Material> RawMaterials { get; set; }
        public List<PostingType> PostingTypes { get; set; }
    }
}

InventoryManagement/Controllers/StockPostingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using InventoryManagement.Models;
using InventoryManagement.ViewModels;

namespace InventoryManagement.Controllers
{
    public class StockPostingController : Controller
    {
        // Define DBContext Object
        private ApplicationDbContext _context;


        public StockPostingController()
        {
            // Initialize DBContext Object
            _context = new ApplicationDbContext();
        }

        // GET: StockPosting
        public ActionResult Index()
        {
            var allPosting = _context.StockPosting_Headers.Include(s => s.PostingType).ToList();
            return View(allPosting);
        }

        [Authorize(Roles = "Admin, WarehouseDept")]
        public ActionResult EnterReferenceOrder(string postingType)
        {

            // Initialize viewModel object
            var viewModel = new EnterOrderViewModel()
            {
                PostingTypeID = postingType,
                OrderID = 0
            };

            return View("EnterOrderForm", viewModel);

        }

        [Authorize(Roles = "Admin, WarehouseDept")]
        public ActionResult New(EnterOrderViewModel eoViewModel)
        {
            // Define view model object
            var viewModel = new StockPostingViewModel();
            List<StockPosting_Item> spItems = new List<StockPosting_Item>();
            StockPosting_Header spHeader = new StockPosting_Header();
            StockPosting_Item spItem = null;

            switch (eoViewModel.PostingTypeID)
            {
                // Work Order GI
                case ConstantsDefintion.GOOD_ISSUE_WORK_ORDER:

                    // Based on Work order items 
                    var woItems = _context.WO_Items.Where(w => w.WO_HeaderID == eoViewModel.OrderID).ToList();



                    // Based on WO item list, initialize stock posting items

                    foreach (var item in woItems)
                    {
                        spItem = new StockPosting_Item();
                        spItem.MaterialID = item.MaterialID;
                        spItem.Quantity = item.Quantity;

                        spItems.Add(spItem);
                    }

                    // Inistialize stock posting header
                    spHeader.ReferenceOrderID = eoViewModel.OrderID;
                    spHeader.DateCreated = DateTime.Now;
                    spHeader.PostingTypeID = byte.Parse(eoViewModel.PostingTypeID);



                    // Initialize viewModel object

                    viewModel.StockPosting_Header = spHeader;
                    viewModel.StockPosting_Items = spItems;


                    viewModel.Products = _context.Materials.Where(m => m.MaterialTypeID == MaterialType.FinishedProduct).ToList();
                    viewModel.RawMaterials = _context.Materials.Where(m => m.MaterialTypeID == MaterialType.RawMaterial).ToList();

                    viewModel.PostingTypes = _context.PostingTypes.ToList();

                    break;

                // Work Order GR
                case ConstantsDefintion.GOOD_RECEIPT_WORK_ORDER:

                    // Based on Work order Header, initialize stock posting item 
                    var woHeader = _context.WO_Headers.Where(w => w.ID == eoViewModel.OrderID).Single();


                    spItem = new StockPosting_Item();
                    spItem.MaterialID = woHeader.ProductID;
                    spItem.Quantity = woHeader.Quantity;

                    spItems.Add(spItem);


                    // Inistialize stock posting header

                    spHeader.ReferenceOrderID = eoViewModel.OrderID;
                    spHeader.DateCreated = DateTime.Now;
                    spHeader.PostingTypeID = byte.Parse(eoViewModel.PostingTypeID);



                    // Initialize viewModel object

                    viewModel.StockPosting_Header = spHeader;
                    viewModel.StockPosting_Items = spItems;


                    viewModel.Products = _context.Materials.Where(m => m.MaterialTypeID == MaterialType.FinishedProduct).ToList();
                    viewModel.RawMaterials = _context.Materials.Where(m => m.MaterialTypeID == MaterialType.RawMaterial).ToList();

                    viewModel.PostingTypes = _context.PostingTypes.ToList();

                    break;
                default:
                    break;
            }

            return View("StockPostingForm", viewModel);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(StockPostingViewModel viewModel)
        {

            // Server side validation
            if (!ModelState.IsValid)
            {
                // The form is not valid -> Return the same form to the user

                return View("viewModel", viewModel);
            }


            // IF FORM IS VALID


            // Add new stock posting record
            if (viewModel.StockPosting_Header.ID == 0)
            {



                // ADD or Deduct the current stock
                foreach (var item in viewModel.StockPosting_Items)
                {
                    // Following material & quantity will be deducted from the current stock
                    int materialID = item.MaterialID;
                    double quantity = item.Quantity;

                    Material material = _context.Materials.Find(materialID);


                    // Work Order Good Issue
                    if (viewModel.StockPosting_Header.PostingTypeID == PostingType.GoodIssue_WorkOrder)
                    {
                        // Deduct the current stock
                        if (material.Quantity < quantity)
                        {
                            // LOW STOCK => TO be implemented (GIVE ERROR MESSAGE)
                        }
                        else
                        {
                            material.Quantity = material.Quantity - quantity;
                        }

                    }
                    // Work Order Good Receipt
                    else if (viewModel.StockPosting_Header.PostingTypeID == PostingType.GoodReceipt_WorkOrder)
                    {
                        // Add to current stock
                        material.Quantity = material.Quantity + quantity;
                    }





                }


                // NEED TO UPDATE ORDER STATUS => To be implemented


                // IMPROVEMENT: Could change view model to save next line code
                viewModel.StockPosting_Header.StockPosting_Items = viewModel.StockPosting_Items;
                _context.StockPosting_Headers.Add(viewModel.StockPosting_Header);
            }
            // Update existing device
            else
            {
                //Will implement
            }

            _context.SaveChanges();

            return RedirectToAction("index");

        }

    }


}

InventoryManagement/Views/StockPosting/EnterOrderForm.cshtml
@model InventoryManagement.ViewModels.EnterOrderViewModel

@{
    ViewBag.Title = "EnterOrderForm";
    Layout = "~/Views/Shared/_MyMasterLayout.cshtml";
}

@switch (Model.PostingTypeID)
{
    // Can not use CONSTANTS
    case "2":
    case "3":
        <h2>Please Enter a Work Order Number:</h2>
        break;

    default:
        break;
}



@using (Html.BeginForm("New", "StockPosting"))
{


    <div class="panel">

        <div class="panel-body">


            <div class="form-group">
                @Html.LabelFor(m => m.OrderID)
                @Html.TextBoxFor(m => m.OrderID, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.OrderID)
            </div>

        </div>
    </div>

    @Html.HiddenFor(m => m.PostingTypeID)

    <div class="row">
        <div class="col-md-2 col-md-offset-10">
            <button type="submit" class="btn btn-default">Choose</button>
        </div>
    </div>


}

InventoryManagement/Views/StockPosting/Index.cshtml
@model IEnumerable<InventoryManagement.Models.StockPosting_Header>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MyMasterLayout.cshtml";
}

<h2>All Stock Posting in the System</h2>

@if (!Model.Any())
{
    <p>There are no Stock Posting</p>
}
else
{


    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Stock Posting ID</th>
                <th>Refrence Order ID</th>
                <th>created Date</th>
                <th>Posting Type</th>
        
            </tr>
        </thead>
        <tbody>
            @foreach (var sp in Model)
            {
                <tr>
                    <td>@sp.ID</td>
                    <td>@sp.ReferenceOrderID</td>
                    <td>@sp.DateCreated.Value.ToShortDateString()</td>
                    <td>@sp.PostingType.Type</td>

                </tr>

            }

        </tbody>
    </table>
}

InventoryManagement/Views/StockPosting/StockPostingForm.cshtml
@model InventoryManagement.ViewModels.StockPostingViewModel

@{
    ViewBag.Title = "StockPostingForm";
    Layout = "~/Views/Shared/_MyMasterLayout.cshtml";
}

<h2>StockPostingForm</h2>

@if (Model.StockPosting_Header.PostingTypeID == 2)
{
    <h2 class="page-title">Work Order Good Issue</h2>
}
else if (Model.StockPosting_Header.PostingTypeID == 3)
{
    <h2 class="page-title">Work Order Good Receipt</h2>
}


@using (Html.BeginForm("Save", "StockPosting"))
{
    @Html.ValidationSummary(true, "Please fix the following errors.")



    <div class="panel">
        <div class="panel-heading">
            <div class="left">
                <H4>Header</H4>
            </div>
            <div class="right">
                <button type="button" class="btn-toggle-collapse"><i class="lnr lnr-chevron-up"></i></button>
            </div>
        </div>

        <div class="panel-body">

            <div class="form-group">
                @Html.LabelFor(m => m.StockPosting_Header.ReferenceOrderID)
                @Html.TextBoxFor(m => m.StockPosting_Header.ReferenceOrderID, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.StockPosting_Header.ReferenceOrderID)
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.StockPosting_Header.DateCreated)
                @Html.TextBoxFor(m => m.StockPosting_Header.DateCreated, "{0:yyyy-MM-dd}", new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.StockPosting_Header.DateCreated)
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.StockPosting_Header.PostingTypeID)
                @Html.DropDownListFor(m => m.StockPosting_Header.PostingTypeID, new SelectList(Model.PostingTypes, "ID", "DisplayType"), "Please select a Posting Type", new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.StockPosting_Header.PostingTypeID)
            </div>
        </div>
    </div>

    <div class="panel">
        <div class="panel-heading">
            <div class="left">
                <H4>Items</H4>
            </div>
            <div class="right">
                <button type="button" class="btn-toggle-collapse"><i class="lnr lnr-chevron-up"></i></button>
            </div>
        </div>

        <div class="panel-body">

            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th>Item No.</th>
                        <th>Material</th>
                        <th>Quantity</th>

                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < Model.StockPosting_Items.Count; i++)
                    {
                        <tr>
                            <td>
                                @(i + 1)
                            </td>
                            <td>

                                @*Html.DropDownListFor(m => m.WO_Items[i].MaterialID, new SelectList(Model.RawMaterials, "ID", "DisplayName"), "Please select a Raw Material", new { @class = "form-control" })

                                    // FIXME: Can not submit if I use selection list
                                *@


                                @Html.TextBoxFor(m => m.StockPosting_Items[i].MaterialID, new { @class = "form-control" })


                            </td>
                            <td>
                                @Html.TextBoxFor(m => m.StockPosting_Items[i].Quantity, new { @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.StockPosting_Items[i].Quantity)

                            </td>

                        </tr>

                        @Html.HiddenFor(m => m.StockPosting_Items[i].ID)
                        @Html.HiddenFor(m => m.StockPosting_Items[i].StockPosting_HeaderID)

                    }

                </tbody>
            </table>

        </div>
    </div>



    @Html.HiddenFor(m => m.StockPosting_Header.ID)
    @Html.AntiForgeryToken();

    <div class="row">
        <div class="col-md-2 col-md-offset-10">
            <button type="submit" class="btn btn-default">Save</button>
        </div>
    </div>


}

@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
}